services:
  php83-fpm:
    container_name: php83
    hostname: php83
    build:
      context: ./php
      dockerfile: ./83/Dockerfile
      args:
        - CUSTOM_USER_NAME=${CUSTOM_USER_NAME}
        - CUSTOM_UID=${CUSTOM_UID}
        - CUSTOM_GID=${CUSTOM_GID}
    restart: ${DOCKER_RESTART}
    volumes:
      - ${DOCUMENTROOT}:/var/www/html:delegated
    dns:
      - 192.168.103.3  # dnsmasq-internal (resolves .test to Apache IP)
    networks:
      lde-network:
    user: ${CUSTOM_UID}:${CUSTOM_GID}
